rm .nlsock.c.swp
rm .nlattr.c.swp
rm .genetlink.c.swp
rm net/.netlink.h.swp
rm net/.genetlink.h.swp
rm net/.rtnetlink.h.swp
rm linux/.netlink.h.swp
rm linux/.genetlink.h.swp
rm linux/.rtnetlink.h.swp
